"use client";
import * as React from 'react';
import { useState, useEffect, useRef } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { useBusiness, Holiday, Profile } from '@/context/BusinessContext';
import { Sparkles, Copy, AlertCircle, Loader2, CalendarDays, Check, BookOpen, Share2, ImageIcon, ArrowLeft, Smartphone, Monitor, Eye } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { useNotification } from '@/components/notifications';
import { parseISO, format } from 'date-fns';
import { createCampaign, scheduleCampaign, updateCampaign, Campaign } from '@/lib/campaigns';
import { createTemplate, generateTemplateName } from '@/lib/templates';
import { logCaptionGenerated, logCampaignScheduled, logTemplateSaved, logPostSimulated } from '@/lib/activity';
import { ImageUpload } from '@/components/post/ImageUpload';
import { InstagramSimulator, FacebookSimulator } from '@/components/simulator';

// Social media SVG components
const InstagramIcon = ({ className }: { className?: string }) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}><rect width="20" height="20" x="2" y="2" rx="5" ry="5"/><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"/><circle cx="17.5" cy="6.5" r="1.5"/></svg>
);

const FacebookIcon = ({ className }: { className?: string }) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}><path d="M18 2h-3a6 6 0 0 0-6 6v3H7v4h2v8h4v-8h3l1-4h-4V8a2 2 0 0 1 2-2h3z"/></svg>
);

export default function CreatePage(): React.ReactElement {
  const { addNotification } = useNotification();
  const params = useParams();
  const router = useRouter();
  const holidayId = params.id as string;
  const { holidays, profile } = useBusiness();
  
  const [loading, setLoading] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [editingCaption, setEditingCaption] = useState(false);
  const [saving, setSaving] = useState(false);
  const [savingTemplate, setSavingTemplate] = useState(false);
  const [posting, setPosting] = useState(false);
  const [campaignId, setCampaignId] = useState<string | null>(null);
  const [previewMode, setPreviewMode] = useState(false);
  const [previewPlatform, setPreviewPlatform] = useState<'instagram' | 'facebook'>('instagram');
  const [previewViewMode, setPreviewViewMode] = useState<'mobile' | 'desktop'>('mobile');
  const [platforms, setPlatforms] = useState({
    instagram: true,
    facebook: false,
  });
  const [content, setContent] = useState<{
    instagram: string;
    email: string;
    hashtags: string[];
    imageUrl: string | null;
  }>({
    instagram: '',
    email: '',
    hashtags: [] as string[],
    imageUrl: null,
  });
  const [engagement, setEngagement] = useState({
    reach: { min: 3500, max: 5000 },
    likes: { min: 250, max: 400 },
    comments: { min: 30, max: 50 },
    shares: { min: 40, max: 70 },
  });
  const [platformTips, setPlatformTips] = useState({
    instagram: 'Use all suggested hashtags and post during peak hours (9-11 AM or 7-9 PM).',
    facebook: 'Include a clear call-to-action and encourage comments. Facebook prioritizes authentic engagement.',
  });
  const [copied, setCopied] = useState(false);
  const [generationNotice, setGenerationNotice] = useState<string | null>(null);
  const [streamingCaption, setStreamingCaption] = useState('');
  const [captionHistory, setCaptionHistory] = useState<string[]>([]);
  const hasAutoGeneratedRef = useRef<string | null>(null);
  const generationInFlightRef = useRef(false);

  const parseCaptionArray = (content: string): string[] => {
    const normalized = (content || '').replace(/^```json\s*|^```\s*|\s*```$/gim, '').trim();
    const arrayMatch = normalized.match(/\[[\s\S]*\]/);
    const candidates = [normalized, arrayMatch?.[0] || ''];

    for (const candidate of candidates) {
      if (!candidate) continue;
      try {
        const parsed = JSON.parse(candidate.replace(/,\s*([}\]])/g, '$1'));
        if (Array.isArray(parsed)) {
          return parsed.map((item) => String(item)).filter(Boolean);
        }
      } catch {
        // continue trying next candidate
      }
    }

    return [];
  };



  const requestSingleCaption = async (priorCaptions: string[] = []) => {
    const response = await fetch('/api/generate-content', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        mode: 'caption',
        stream: priorCaptions.length === 0,
        holidayName: holiday?.name,
        businessName: profile?.name,
        businessType: profile?.type || 'Business',
        businessNiche: profile?.description || profile?.type || 'General',
        tone: profile?.tone || 'Friendly',
        targetAudience: profile?.targetAudience || 'Customers',
        platform: getActivePlatform(),
        previousCaptions: priorCaptions,
        eventDate: holiday?.date,
      }),
    });

    if (!response.ok) {
      const errorJson = await response.json().catch(() => ({}));
      const errorMessage = errorJson?.error || 'Failed to regenerate caption';
      throw new Error(errorMessage);
    }

    const contentType = response.headers.get('content-type') || '';
    if (contentType.includes('application/json')) {
      const jsonData = await response.json();
      return Array.isArray(jsonData.captions) ? jsonData.captions.slice(0, 1) : [];
    }

    if (!response.body) {
      return [];
    }

    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let streamedText = '';

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;

      const chunk = decoder.decode(value, { stream: true });
      streamedText += chunk;
      setStreamingCaption(streamedText);
      setContent((prev) => ({ ...prev, instagram: streamedText }));
    }

    const parsedCaptions = parseCaptionArray(streamedText);
    if (parsedCaptions.length > 0) {
      return parsedCaptions.slice(0, 1);
    }

    const fallbackCaption = streamedText.trim();
    return fallbackCaption ? [fallbackCaption] : [];
  };

  const holiday = holidays.find(h => String(h.id) === holidayId);


  // Helper functions for fallback content generation
  const generateFallbackCaption = (holiday: Holiday, profile: Profile) => {
    return `🎉 Happy ${holiday.name}! 🎊

Join us at ${profile.name} as we celebrate this special occasion with amazing experiences tailored for ${profile.targetAudience}.

Whether you're celebrating with friends, family, or your loved ones, we've got something special prepared just for you this ${holiday.name}! 

📍 Find us in ${profile.location || 'our area'}
🔗 Link in bio for more details`;
  };

  // Restore state from localStorage when returning from simulator
  const hasRestoredRef = useRef(false);
  useEffect(() => {
    if (hasRestoredRef.current) return;
    const savedState = localStorage.getItem(`create-page-state-${holidayId}`);
    if (savedState) {
      try {
        const parsed = JSON.parse(savedState);
        console.log('[CreatePage] Found saved state:', { hasImage: !!parsed.content?.imageUrl, hasCaption: !!parsed.content?.instagram, timestamp: parsed.timestamp });
        // Only restore if saved within last 30 minutes
        if (parsed.timestamp && Date.now() - parsed.timestamp < 30 * 60 * 1000) {
          // Restore if we have any content (caption, image, or hashtags)
          if (parsed.content && (parsed.content.instagram || parsed.content.imageUrl || parsed.content.hashtags?.length > 0)) {
            console.log('[CreatePage] Restoring content with imageUrl:', parsed.content.imageUrl);
            setContent(parsed.content);
          }
          if (parsed.platforms) {
            setPlatforms(parsed.platforms);
          }
          if (parsed.campaignId) {
            setCampaignId(parsed.campaignId);
          }
          // Mark as generated to prevent auto-generation BEFORE clearing storage
          hasRestoredRef.current = true;
          setGenerated(true);
          // Clear the saved state after restoration
          localStorage.removeItem(`create-page-state-${holidayId}`);
          console.log('[CreatePage] State restored successfully');
        } else {
          // Clear stale state
          localStorage.removeItem(`create-page-state-${holidayId}`);
        }
      } catch (e) {
        console.error('Failed to restore state:', e);
        localStorage.removeItem(`create-page-state-${holidayId}`);
      }
    }
  }, [holidayId]);

  useEffect(() => {
    if (!holiday || !profile || generated || loading) {
      return;
    }

    if (hasAutoGeneratedRef.current === holidayId) {
      return;
    }

    // Check if there's saved state to restore (returning from simulator)
    const savedState = localStorage.getItem(`create-page-state-${holidayId}`);
    if (savedState) {
      // Don't auto-generate if we have saved state to restore
      return;
    }

    hasAutoGeneratedRef.current = holidayId;

    const generateContent = async () => {
      if (!holiday || !profile) return;
      if (generationInFlightRef.current) return;

      generationInFlightRef.current = true;
      setLoading(true);
      try {
        const requestBody = {
          holiday: holiday.name,
          holidayDescription: holiday.description || '',
          businessType: profile.type || 'Business',
          businessName: profile.name || 'My Business',
          businessDescription: profile.description || '',
          targetAudience: profile.targetAudience || 'Customers',
          location: profile.location || 'Local Area',
        };

        console.log('Sending to /api/generate-content:', requestBody);

        const response = await fetch('/api/generate-content', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(requestBody),
        });

        console.log('API response status:', response.status);
        
        const data = await response.json();
        console.log('API response data:', data);

        if (!response.ok) {
          console.error('API error response:', data);
          const defaultHashtags = [
            `#${holiday.name.replace(/\s+/g, '')}`,
            '#SmallBusiness',
            '#LocalBusiness',
            '#MarketingTips',
            '#HolidayDeals',
            '#SpecialOffer',
          ];

          setContent({
            instagram: generateFallbackCaption(holiday, profile),
            email: `Subject: 🎉 Celebrate ${holiday.name} with ${profile.name}!\n\nDear Valued ${profile.targetAudience},\n\nThis ${holiday.name}, we're excited to invite you to celebrate with us at ${profile.name}!\n\nWe've curated special ${holiday.name} experiences and exclusive offers just for our community. Whether you're celebrating with friends, family, or treating yourself, we have something special waiting for you.\n\nVisit us and discover why your neighbors love us. We look forward to making your ${holiday.name} memorable!\n\nWarm regards,\n${profile.name} Team\n📍 ${profile.location || 'Our Location'}`,
            hashtags: defaultHashtags,
            imageUrl: null,
          });
          setGenerated(true);
          setGenerationNotice('Groq token limit reached. Showing a fallback draft.');
          addNotification('Using template content. Connect your Groq API for AI-powered content.', 'info');
          return;
        }
        
        const defaultHashtags = [
          `#${holiday.name.replace(/\s+/g, '')}`,
          '#SmallBusiness',
          '#LocalBusiness',
          '#MarketingTips',
          '#HolidayDeals',
          '#SpecialOffer',
        ];

        const newCaptions = Array.isArray(data.instagram)
          ? data.instagram.slice(0, 1)
          : [data.instagram || generateFallbackCaption(holiday, profile)];

        setContent({
          instagram: newCaptions[0],
          email: data.email || `Subject: 🎉 ${holiday.name} Special Offers at ${profile.name}!`,
          hashtags: defaultHashtags,
          imageUrl: null,
        });
        setCaptionHistory(prev => [...prev, newCaptions[0]].slice(-10));
        
        // AI-generated engagement metrics and tips received but not displayed
        // (Predicted Engagement feature removed)
        
        if (data.rateLimited) {
          setGenerationNotice('Groq token limit reached. Showing a fallback draft.');
          addNotification('API token limit reached. Generating template content instead.', 'warning');
        } else if (data.isFallback) {
          setGenerationNotice(null);
          addNotification('Using template content. Connect your Groq API for AI-powered content.', 'info');
        } else {
          setGenerationNotice(null);
        }
        
        setGenerated(true);
        
        // Log caption generation
        try {
          await logCaptionGenerated(
            data.instagram || generateFallbackCaption(holiday, profile),
            defaultHashtags,
            holidayId,
            holiday.name,
            undefined,
            false
          );
        } catch (logError) {
          console.error('Failed to log caption generation:', logError);
        }
        
        // Auto-save campaign draft
        try {
          // First check if campaign already exists for this holiday
          let cId: string | undefined;
          try {
            const campaigns = await fetch('/api/campaigns').then(r => r.json()).then(d => d.campaigns);
            const existing = campaigns.find((c: Campaign) => c.holiday_id === holidayId);
            if (existing) {
              cId = existing.id;
              // Update the existing campaign with new content
              await updateCampaign(existing.id, {
                content: {
                  instagram: data.instagram || generateFallbackCaption(holiday, profile),
                  email: data.email || `Subject: 🎉 ${holiday.name} Special Offers at ${profile.name}!`,
                  hashtags: defaultHashtags,
                  imageUrl: null,
                },
              });
            }
          } catch {
            console.debug('Could not fetch existing campaigns');
          }

          // If no existing campaign, create a new one
          if (!cId) {
            const campaign = await createCampaign(
              holidayId,
              {
                instagram: data.instagram || generateFallbackCaption(holiday, profile),
                email: data.email || `Subject: 🎉 ${holiday.name} Special Offers at ${profile.name}!`,
                hashtags: defaultHashtags,
                imageUrl: null,
              },
              platforms,
              null
            );
            cId = campaign.id;
          }

          setCampaignId(cId);
        } catch (error) {
          console.error('Error auto-saving campaign draft:', error);
          // Continue anyway - draft save is not critical
        }
      } catch (error) {
        console.error('Failed to generate content:', error);
        const defaultHashtags = [
          `#${holiday.name.replace(/\s+/g, '')}`,
          '#SmallBusiness',
          '#LocalBusiness',
          '#MarketingTips',
          '#HolidayDeals',
          '#SpecialOffer',
        ];

        setContent({
          instagram: generateFallbackCaption(holiday, profile),
          email: `Subject: 🎉 Celebrate ${holiday.name} with ${profile.name}!\n\nDear Valued ${profile.targetAudience},\n\nThis ${holiday.name}, we're excited to invite you to celebrate with us at ${profile.name}!\n\nWe've curated special ${holiday.name} experiences and exclusive offers just for our community. Whether you're celebrating with friends, family, or treating yourself, we have something special waiting for you.\n\nVisit us and discover why your neighbors love us. We look forward to making your ${holiday.name} memorable!\n\nWarm regards,\n${profile.name} Team\n📍 ${profile.location || 'Our Location'}`,
          hashtags: defaultHashtags,
          imageUrl: null,
        });
        setGenerated(true);
        setGenerationNotice('Groq token limit reached. Showing a fallback draft.');
        addNotification('Using template content. Connect your Groq API for AI-powered content.', 'info');
      } finally {
        generationInFlightRef.current = false;
        setLoading(false);
      }
    };

    generateContent();
  }, [holiday, profile, holidayId, generated, loading, platforms, addNotification]);

  const handleRegenerateCaption = async () => {
  if (!holiday || !profile) return;
  if (generationInFlightRef.current) return;

  generationInFlightRef.current = true;
  setLoading(true);
  setStreamingCaption('');

  try {
    const priorCaptions = content.instagram ? [...captionHistory, content.instagram] : captionHistory;
    const nextCaptions = await requestSingleCaption(priorCaptions);

    if (nextCaptions.length > 0) {
      setContent((prev) => ({ ...prev, instagram: nextCaptions[0] }));
      setCaptionHistory(prev => [...prev, nextCaptions[0]].slice(-10));
      addNotification('New caption generated!', 'success');
      
      // Log caption regeneration
      try {
        await logCaptionGenerated(
          nextCaptions[0],
          content.hashtags,
          holidayId,
          holiday?.name || '',
          campaignId || undefined,
          true
        );
      } catch (logError) {
        console.error('Failed to log caption regeneration:', logError);
        addNotification(logError instanceof Error ? logError.message : 'Failed to log caption regeneration', 'error');
      }
    }
  } catch (error) {
    console.error('Failed to regenerate caption:', error);
    addNotification(error instanceof Error ? error.message : 'Failed to regenerate caption', 'error');
  } finally {
    setStreamingCaption('');
    generationInFlightRef.current = false; // Reset the ref here
    setLoading(false);
  }
};

  const handlePlatformChange = (key: keyof typeof platforms) => {
    setPlatforms({ instagram: false, facebook: false, [key]: true });
  };

  const handleCopy = () => {
    const fullText = `${content.instagram}\n\n${content.hashtags.join(' ')}`;
    navigator.clipboard.writeText(fullText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    addNotification('Copied to clipboard!', 'success');
  };

  const handleSaveTemplate = async () => {
    if (!content.instagram) {
      addNotification('No content to save as template', 'error');
      return;
    }

    setSavingTemplate(true);
    try {
      const activePlatforms = Object.entries(platforms)
        .filter(([, enabled]) => enabled)
        .map(([name]) => name);

      const templateName = generateTemplateName(content.instagram, holiday?.name);

      const result = await createTemplate({
        name: templateName,
        content: content.instagram,
        hashtags: content.hashtags,
        category: 'holiday',
        holiday_name: holiday?.name,
        business_type: profile?.type,
        tone: profile?.tone,
        platforms: activePlatforms,
      });

      if (result) {
        addNotification('Template saved to Content Library!', 'success');
        
        // Log template save
        try {
          await logTemplateSaved(
            templateName,
            holiday?.name || '',
            activePlatforms
          );
        } catch (logError) {
          console.error('Failed to log template save:', logError);
        }
      } else {
        addNotification('Failed to save template', 'error');
      }
    } catch (error) {
      console.error('Error saving template:', error);
      addNotification('Failed to save template', 'error');
    } finally {
      setSavingTemplate(false);
    }
  };

  const getActivePlatform = () => {
    if (platforms.instagram) return 'instagram';
    if (platforms.facebook) return 'facebook';
    return 'instagram';
  };

  const handleEditDone = async () => {
    setEditingCaption(false);
    
    // Auto-save edited content
    if (campaignId) {
      try {
        await updateCampaign(campaignId, {
          content,
        });
        addNotification('Caption saved!', 'success');
      } catch (error) {
        console.error('Error saving caption:', error);
        addNotification('Failed to save caption', 'error');
      }
    }
  };

  const handleSchedule = async () => {
    if (!holiday || !profile) return;

    setSaving(true);
    try {
      // First, check if campaign already exists
      let cId = campaignId;
      
      if (!cId) {
        // Try to fetch existing campaigns to find one for this holiday
        try {
          const campaigns = await fetch('/api/campaigns').then(r => r.json()).then(data => data.campaigns);
          const existing = campaigns.find((c: Campaign) => c.holiday_id === holidayId);
          if (existing) {
            cId = existing.id;
            setCampaignId(existing.id);
          }
        } catch {
          // If fetching fails, continue and try to create
        }
      }
      
      if (!cId) {
        // Create campaign if it doesn't exist
        const campaign = await createCampaign(
          holidayId,
          content,
          platforms,
          format(parseISO(holiday.date), 'yyyy-MM-dd')
        );
        cId = campaign.id;
        setCampaignId(cId);
        addNotification('Campaign created!', 'success');
      } else {
        // Update existing campaign with latest content
        await updateCampaign(cId, {
          content,
          platforms,
        });
        addNotification('Campaign updated!', 'success');
      }

      // Schedule the campaign
      await scheduleCampaign(
        cId,
        format(parseISO(holiday.date), 'yyyy-MM-dd'),
        platforms
      );

      addNotification('Campaign scheduled successfully!', 'success');
      
      // Log campaign scheduling
      try {
        const selectedPlatforms = Object.entries(platforms)
          .filter(([, enabled]) => enabled)
          .map(([name]) => name as 'instagram' | 'facebook');
        
        await logCampaignScheduled(
          holidayId,
          holiday?.name || '',
          cId,
          selectedPlatforms,
          format(parseISO(holiday.date), 'yyyy-MM-dd')
        );
      } catch (logError) {
        console.error('Failed to log campaign scheduling:', logError);
      }
      
      // Redirect to dashboard after a short delay
      setTimeout(() => {
        router.push('/');
      }, 1500);
    } catch (error) {
      console.error('Error scheduling campaign:', error);
      addNotification('Failed to schedule campaign', 'error');
    } finally {
      setSaving(false);
    }
  };

  const handlePreviewBack = () => {
    setPreviewMode(false);
  };

  const handleConfirmSimulation = async () => {
    if (!campaignId) {
      addNotification('No campaign to post', 'error');
      return;
    }

    setPosting(true);

    try {
      // Simulate posting delay
      await new Promise(resolve => setTimeout(resolve, 1500));

      // Generate simulated post ID
      const postId = `${previewPlatform}_${Date.now()}_${Math.random().toString(36).substring(2, 8)}`;

      // Log the simulation
      await logPostSimulated(
        [previewPlatform],
        content.instagram,
        content.hashtags,
        holidayId,
        holiday?.name || '',
        campaignId,
        { success: true, platform: previewPlatform, postId },
        { [previewPlatform]: postId }
      );

      addNotification(`Simulated post to ${previewPlatform === 'instagram' ? 'Instagram' : 'Facebook'}!`, 'success');

      // Exit preview mode and redirect to dashboard
      setTimeout(() => {
        router.push('/');
      }, 1000);
    } catch (error) {
      console.error('Error during simulation:', error);
      addNotification('Failed to complete simulation', 'error');
    } finally {
      setPosting(false);
    }
  };

  const handlePostNow = async () => {
    if (!holiday || !profile) return;

    const selectedPlatforms = Object.entries(platforms)
      .filter(([, enabled]) => enabled)
      .map(([name]) => name as 'instagram' | 'facebook');

    if (selectedPlatforms.length === 0) {
      addNotification('Please select at least one platform', 'error');
      return;
    }

    // For now, only support single platform simulation (first selected)
    const platform = selectedPlatforms[0];

    setPosting(true);
    try {
      // First, ensure campaign exists
      let cId = campaignId;

      if (!cId) {
        try {
          const campaigns = await fetch('/api/campaigns').then(r => r.json()).then(data => data.campaigns);
          const existing = campaigns.find((c: Campaign) => c.holiday_id === holidayId);
          if (existing) {
            cId = existing.id;
            setCampaignId(existing.id);
          }
        } catch {
          // Continue if fetch fails
        }
      }

      if (!cId) {
        const campaign = await createCampaign(
          holidayId,
          content,
          platforms,
          null
        );
        cId = campaign.id;
        setCampaignId(cId);
      } else {
        await updateCampaign(cId, { content, platforms });
      }

      // Save current state to localStorage for restoration when returning
      const stateToSave = {
        content,
        platforms,
        campaignId: cId,
        holidayId,
        timestamp: Date.now(),
      };
      localStorage.setItem(`create-page-state-${holidayId}`, JSON.stringify(stateToSave));

      // Switch to preview mode inline instead of navigating away
      setPreviewPlatform(platform);
      setPreviewMode(true);
      window.scrollTo({ top: 0, behavior: 'smooth' });
    } catch (error) {
      console.error('Error preparing simulation:', error);
      addNotification('Failed to prepare simulation', 'error');
    } finally {
      setPosting(false);
    }
  };

  if (!holiday) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Card className="border-destructive/50 bg-destructive/5">
          <CardContent className="flex flex-col items-center gap-4 pt-6">
            <AlertCircle className="w-12 h-12 text-destructive" />
            <p className="text-lg font-semibold text-foreground">Holiday not found</p>
            <Button onClick={() => router.push('/holidays')} variant="outline">
              Back to Calendar
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen py-6 space-y-6">
      {/* Preview Mode */}
      {previewMode ? (
        <div className="space-y-6">
          {/* Preview Header */}
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Button
                variant="ghost"
                onClick={handlePreviewBack}
                className="flex items-center gap-2 text-muted-foreground hover:text-foreground"
              >
                <ArrowLeft className="w-5 h-5" />
                <span className="hidden sm:inline">Back to Edit</span>
              </Button>
              <div>
                <h2 className="text-xl font-semibold">Preview Your Post</h2>
                <p className="text-sm text-muted-foreground">
                  {previewPlatform === 'instagram' ? 'Instagram' : 'Facebook'} • {previewViewMode === 'mobile' ? 'Mobile' : 'Web'}
                </p>
              </div>
            </div>

            <div className="flex items-center gap-3">
              {/* View Mode Toggle */}
              <div className="flex items-center gap-1 bg-muted rounded-lg p-1">
                <button
                  onClick={() => setPreviewViewMode('mobile')}
                  className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-sm font-medium transition-all ${
                    previewViewMode === 'mobile'
                      ? 'bg-background shadow-sm'
                      : 'text-muted-foreground hover:bg-background/50'
                  }`}
                >
                  <Smartphone className="w-4 h-4" />
                  Mobile
                </button>
                <button
                  onClick={() => setPreviewViewMode('desktop')}
                  className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-sm font-medium transition-all ${
                    previewViewMode === 'desktop'
                      ? 'bg-background shadow-sm'
                      : 'text-muted-foreground hover:bg-background/50'
                  }`}
                >
                  <Monitor className="w-4 h-4" />
                  Web
                </button>
              </div>

              {/* Platform Toggle */}
              <div className="flex items-center gap-1 bg-muted rounded-lg p-1">
                <button
                  onClick={() => setPreviewPlatform('instagram')}
                  className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-sm font-medium transition-all ${
                    previewPlatform === 'instagram'
                      ? 'bg-background shadow-sm'
                      : 'text-muted-foreground hover:bg-background/50'
                  }`}
                >
                  <InstagramIcon className="w-4 h-4" />
                  Instagram
                </button>
                <button
                  onClick={() => setPreviewPlatform('facebook')}
                  className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-sm font-medium transition-all ${
                    previewPlatform === 'facebook'
                      ? 'bg-background shadow-sm'
                      : 'text-muted-foreground hover:bg-background/50'
                  }`}
                >
                  <FacebookIcon className="w-4 h-4" />
                  Facebook
                </button>
              </div>
            </div>
          </div>

          {/* Preview Content */}
          <div className="grid lg:grid-cols-[1fr,380px] gap-6">
            {/* Simulator */}
            <div className="flex justify-center">
              <div className={`
                overflow-hidden rounded-2xl shadow-xl transition-all duration-500
                ${previewViewMode === 'mobile' ? 'w-[375px] max-w-full' : 'w-full max-w-6xl'}
              `}>
                {previewPlatform === 'instagram' ? (
                  <InstagramSimulator
                    caption={content.instagram}
                    hashtags={content.hashtags}
                    imageUrl={content.imageUrl}
                    businessName={profile?.name || 'Your Business'}
                    location={profile?.location || ''}
                    viewMode={previewViewMode}
                  />
                ) : (
                  <FacebookSimulator
                    caption={content.instagram}
                    hashtags={content.hashtags}
                    imageUrl={content.imageUrl}
                    businessName={profile?.name || 'Your Business'}
                    location={profile?.location || ''}
                    viewMode={previewViewMode}
                  />
                )}
              </div>
            </div>

            {/* Actions Panel */}
            <div className="space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Eye className="w-5 h-5" />
                    Ready to Post?
                  </CardTitle>
                  <CardDescription>
                    Review your post in the preview. Everything looks good?
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="space-y-2 text-sm">
                    <p><span className="font-medium">Platform:</span> {previewPlatform === 'instagram' ? 'Instagram' : 'Facebook'}</p>
                    <p><span className="font-medium">Business:</span> {profile?.name}</p>
                    <p><span className="font-medium">Image:</span> {content.imageUrl ? '✓ Uploaded' : '✗ None'}</p>
                    <p><span className="font-medium">Hashtags:</span> {content.hashtags.length}</p>
                  </div>

                  <Button
                    onClick={handleConfirmSimulation}
                    disabled={posting}
                    className={`w-full h-11 font-semibold ${
                      previewPlatform === 'instagram'
                        ? 'bg-gradient-to-r from-purple-600 via-pink-500 to-orange-400'
                        : 'bg-[#1877f2]'
                    }`}
                  >
                    {posting ? (
                      <>
                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        Processing...
                      </>
                    ) : (
                      <>
                        <Check className="w-4 h-4 mr-2" />
                        Confirm & Simulate
                      </>
                    )}
                  </Button>

                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      ) : (
        <>
          {/* Header Banner */}
          <div className="bg-primary rounded-2xl p-6 md:p-8 text-white relative overflow-hidden">
            <div className="absolute inset-0 bg-white/10 backdrop-blur-sm"></div>
            <div className="relative z-10 flex items-start justify-between">
              <div>
                <div className="flex items-center gap-3 mb-3">
                  <CalendarDays className="w-6 h-6" />
                  <h1 className="text-3xl md:text-4xl font-extrabold">{holiday.name}</h1>
                  <Badge variant="secondary" className="bg-white/20 hover:bg-white/30 text-white border-white/30">
                    {format(parseISO(holiday.date), 'MMM dd, yyyy')}
                  </Badge>
                </div>
                <p className="text-white/90 text-lg">{holiday.description}</p>
              </div>
              <Sparkles className="w-12 h-12 opacity-50" />
            </div>
          </div>

      {/* Main Content - Full width matching header */}
      <div className="space-y-6">
          {/* AI-Generated Caption Card */}
          <Card className="border-white/20 bg-card/60 backdrop-blur-xl">
            <CardHeader className="pb-4">
              <div className="flex items-center justify-between">
                <CardTitle className="flex items-center gap-2">
                  <Sparkles className="w-5 h-5 text-primary" />
                  AI-Generated Caption
                </CardTitle>
                <div className="flex gap-2 items-center">
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => {
                      if (editingCaption) {
                        handleEditDone();
                      } else {
                        setEditingCaption(true);
                      }
                    }}
                    className="text-primary hover:bg-primary/10"
                  >
                    {editingCaption ? <Check className="w-4 h-4 mr-1" /> : <Copy className="w-4 h-4 mr-1" />}
                    {editingCaption ? 'Done' : 'Edit'}
                  </Button>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={handleRegenerateCaption}
                    disabled={loading}
                    className="text-primary hover:bg-primary/10"
                  >
                    {loading ? <Loader2 className="w-4 h-4 animate-spin mr-1" /> : <Sparkles className="w-4 h-4 mr-1" />}
                    Regenerate
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
                {generationNotice && (
                  <div className="rounded-md border border-amber-500/30 bg-amber-500/10 px-3 py-2 text-xs text-amber-700 dark:text-amber-300">
                    {generationNotice}
                  </div>
                )}
              {loading ? (
                <div className="flex flex-col items-center justify-center p-8 gap-3">
                  <Loader2 className="w-8 h-8 animate-spin text-primary" />
                  <p className="text-muted-foreground font-medium">
                    {streamingCaption ? 'Streaming caption...' : 'Generating content...'}
                  </p>
                  {streamingCaption && (
                    <div className="w-full bg-background/60 border border-white/10 rounded-lg p-4 min-h-20">
                      <p className="text-foreground whitespace-pre-wrap">{streamingCaption}</p>
                    </div>
                  )}
                </div>
              ) : (
                <>
                  {editingCaption ? (
                    <textarea
                      value={content.instagram}
                      onChange={(e) => setContent({ ...content, instagram: e.target.value })}
                      className="w-full bg-background/60 border border-primary/50 rounded-lg p-4 min-h-40 text-foreground focus:outline-none focus:ring-2 focus:ring-primary resize-none"
                      placeholder="Edit your caption here..."
                    />
                  ) : (
                    <div className="bg-background/60 border border-white/10 rounded-lg p-4 min-h-32">
                      <p className="text-foreground whitespace-pre-wrap">{content.instagram}</p>
                    </div>
                  )}

                  {/* Hashtags */}
                  <div>
                    <p className="text-xs font-semibold text-muted-foreground mb-3 uppercase tracking-wider">Suggested Hashtags</p>
                    <div className="flex flex-wrap gap-2">
                      {content.hashtags.map((tag) => (
                        <Badge key={tag} variant="secondary" className="bg-primary/10 text-primary hover:bg-primary/20">
                          {tag}
                        </Badge>
                      ))}
                    </div>
                  </div>

                  <Button 
                    onClick={handleCopy}
                    className="w-full bg-primary hover:bg-primary-dark"
                  >
                    {copied ? <Check className="w-4 h-4 mr-2 text-green-500" /> : <Copy className="w-4 h-4 mr-2" />}
                    {copied ? "Copied!" : "Copy Caption + Hashtags"}
                  </Button>

                  <Button 
                    onClick={handleSaveTemplate}
                    disabled={savingTemplate || !content.instagram}
                    variant="outline"
                    className="w-full"
                  >
                    {savingTemplate ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <BookOpen className="w-4 h-4 mr-2" />}
                    {savingTemplate ? "Saving..." : "Save to Templates"}
                  </Button>
                </>
              )}
            </CardContent>
          </Card>

          {/* Image Upload */}
          <Card className="border-white/20 bg-card/60 backdrop-blur-xl">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <ImageIcon className="w-5 h-5 text-primary" />
                Post Image
              </CardTitle>
              <CardDescription>Upload or generate an image for your post</CardDescription>
            </CardHeader>
            <CardContent>
              <ImageUpload
                holidayId={holidayId}
                imageUrl={content.imageUrl}
                onImageChange={(url) => setContent({ ...content, imageUrl: url })}
              />
            </CardContent>
          </Card>

          {/* Select Platforms Card */}
          <Card className="border-white/20 bg-card/60 backdrop-blur-xl">
            <CardHeader>
              <CardTitle>Select Platforms</CardTitle>
              <CardDescription>Choose where you want to post this content</CardDescription>
            </CardHeader>
            <CardContent className="space-y-3">
              {[
                { key: 'instagram', label: 'Instagram', icon: InstagramIcon },
                { key: 'facebook', label: 'Facebook', icon: FacebookIcon },
              ].map(({ key, label, icon: Icon }) => (
                <button
                  key={key}
                  onClick={() => handlePlatformChange(key as keyof typeof platforms)}
                  className={`w-full flex items-center justify-between p-4 rounded-lg border-2 transition-all ${
                    platforms[key as keyof typeof platforms]
                      ? 'border-primary bg-primary/10'
                      : 'border-white/10 hover:border-white/20'
                  }`}
                >
                  <div className="flex items-center gap-3">
                    <Icon className={`w-5 h-5 ${platforms[key as keyof typeof platforms] ? 'text-primary' : 'text-muted-foreground'}`} />
                    <span className="font-medium">{label}</span>
                  </div>
                  {platforms[key as keyof typeof platforms] && <Check className="w-4 h-4 text-primary" />}
                </button>
              ))}
            </CardContent>
          </Card>

          {/* Action Buttons */}
          <div className="space-y-3">
            {/* Primary: Preview Button - Show if at least one platform is selected */}
            {(platforms.instagram || platforms.facebook) && (
              <Button 
                onClick={handlePostNow}
                disabled={posting}
                className="w-full h-14 bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-700 hover:to-emerald-700 text-base font-bold shadow-lg shadow-green-600/20"
              >
                {posting ? (
                  <>
                    <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                    Preparing Preview...
                  </>
                ) : (
                  <>
                    <Eye className="w-5 h-5 mr-2" />
                    Preview on {[
                      platforms.instagram && 'Instagram',
                      platforms.facebook && 'Facebook'
                    ].filter(Boolean).join(' & ')}
                  </>
                )}
              </Button>
            )}

            {/* Secondary: Schedule Button */}
            <Button 
              onClick={handleSchedule}
              disabled={saving}
              variant="outline"
              className="w-full h-12 text-base font-semibold border-2 hover:bg-primary/5"
            >
              {saving ? (
                <>
                  <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                  Scheduling...
                </>
              ) : (
                <>
                  <CalendarDays className="w-5 h-5 mr-2" />
                  Schedule for {format(parseISO(holiday.date), 'MMM dd')}
                </>
              )}
            </Button>
          </div>
      </div>
    </>)}
    </div>
  );
}

